### ISSUE TITLE
Changing ways to store the shape info

### ISSUE THREAD

**Issue by yang6lang1** [BlockadiaTeam/Blockadia-Team-Project#18]
Originally, shape is store as a 2D Color array which is a waste of memory because it's comment that the user leaves a lot of spaces empty. Also, its hard to check weather the grid is dirty or not. So I need to change the storing data structure

**Comment by yang6lang1** [comment]
Issue #9 and #17 are based on this. Remember to close them when this is done

**Comment by yang6lang1** [comment]
Ready for code  review & testing

**Comment by pslam92117** [comment]
Tested. No bugs found.
