### ISSUE TITLE
Should edit grid panel clear upon resizing?

### ISSUE THREAD

**Issue by pslam92117** [BlockadiaTeam/Blockadia-Team-Project#19]
If the user edits a shape and changes the resolution of the grid, will we make it so that it will clear the shape in the grid or have the next chosen resolution carry the shape onto it? This decision must be made when resizing from big to small and from small to big grid size.

**Comment by yang6lang1** [comment]
I think just clearing the grid will be OK. There will be a lot of issues arising when you allow them to inherit the painted shape.

**Comment by pslam92117** [comment]
There should be a button for clearing as well. This should exist in NewShapeSidePanel too.

**Comment by yang6lang1** [comment]
yea the clear button is added
