### ISSUE TITLE
Implement the shapePreview label

### ISSUE THREAD

**Issue by yang6lang1** [BlockadiaTeam/Blockadia-Team-Project#5]
To do this, you might need to read the GameModel.java and GameSidePanel.java(especially the ActionPerformed() method). I was wrong before, the Config.java might not be related to this
After reading those, probably you should create a new class to extend JPanel and override the paintComponent method. There will rise some issues like "when you paint the label, what should be the background color", currently it's black but I believe you can make decisions to make it pretty. GOOD LUCK WITH YOUR FIRST ISSUE. 

OH! Don't forget the put your name int the new class you are going to create! :P

**Comment by pslam92117** [comment]
The preview panel is complete. The grid is purposely not shown to reduce clutter. Previews for all shapes show up accordingly in the preview panel. Tested with all resolutions. A new class was created for this issue called "PreviewPanel"

**Comment by pslam92117** [comment]
The border needs to be fixed. 40x40 preview is buggy since the left and top border covers the first rows and columns. Perhaps a new window should be placed behind it to give the appearance of a border so that it does not interfere with the preview panel itself and the shapes loaded inside it.

**Comment by yang6lang1** [comment]
This has been fixed by putting previewPanel on top of a borderPanel so we don't need to worry about the calculation of border painting in previewPanel. g2.scale is OP.
Ready for code review!
